apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fileguard.configMapName" . }}
  labels:
    {{- include "fileguard.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  MAX_FILE_SIZE_MB: {{ .Values.config.maxFileSizeMb | quote }}
  WORKER_CONCURRENCY: {{ .Values.config.workerConcurrency | quote }}
  ALLOWED_MIME_TYPES: {{ .Values.config.allowedMimeTypes | quote }}
